'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { Archive,ArrowDown,ArrowRight,ArrowUp,BookOpen,CalendarDays,Check,CheckCheck,ChevronDown,ChevronRight,Clock,FolderOpen,Inbox,Layers,List,LayoutGrid,Moon,MoreHorizontal,Plus,RotateCcw,Search,Settings2,Sun,Trash2,Flag,PanelLeft,Play,Command } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { SidebarProvider,Sidebar,SidebarContent,SidebarFooter,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger,DropdownMenuSeparator } from '@/components/ui/dropdown-menu';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster,toast } from 'sonner';
import { Choice,Field,Blank,duration,prettyDate } from '@/components/workspace-parts';
import { TaskDetail } from '@/components/task-detail';
import { useWorkspace } from '@/lib/use-workspace';
import { localDate,makeTask,sampleWorkspace,statusLabels,statuses,type Task,type Project } from '@/lib/domain/workspace';
const navigation=[{id:'today',name:'Today',icon:Sun},{id:'inbox',name:'Inbox',icon:Inbox},{id:'upcoming',name:'Upcoming',icon:CalendarDays},{id:'all',name:'All tasks',icon:Layers}];
export default function Page(){return <SidebarProvider style={{'--sidebar-width':'245px'} as React.CSSProperties}><WorkspaceApp/><Toaster position="bottom-right" richColors/></SidebarProvider>}
function WorkspaceApp(){
 const store=useWorkspace();const {workspace:w,mutate,busy,demo,identity}=store;const {setOpenMobile}=useSidebar();
 const [view,setView]=useState('today');const [layout,setLayout]=useState('list');const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [priority,setPriority]=useState('all');const [sort,setSort]=useState('position');const [selected,setSelected]=useState<string[]>([]);const [opened,setOpened]=useState('');const [create,setCreate]=useState(false);const [title,setTitle]=useState('');const [captureProject,setCaptureProject]=useState('');const [captureStatus,setCaptureStatus]=useState<Task['status']>('todo');const [quick,setQuick]=useState('');const [project,setProject]=useState<Project|null>(null);const [dark,setDark]=useState(false);const [preferencesReady,setPreferencesReady]=useState(false);const [,tick]=useState(0);const search=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('continuum-preferences')||'{}');setDark(!!p.dark);setLayout(p.layout||'list');setView(p.view||'today');setSort(p.sort||'position');setFilter(p.filter||'all');setPriority(p.priority||'all');setQuery(p.query||'')}catch{}setPreferencesReady(true);const timer=setInterval(()=>tick(x=>x+1),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);if(preferencesReady)try{localStorage.setItem('continuum-preferences',JSON.stringify({dark,layout,view,sort,filter,priority,query}))}catch{}},[dark,layout,view,sort,filter,priority,query,preferencesReady]);
 useEffect(()=>{function keys(e:KeyboardEvent){const typing=(e.target as HTMLElement)?.closest('input,textarea,[contenteditable="true"]');if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();search.current?.focus()}if(e.key==='n'&&!typing&&!opened&&!create){e.preventDefault();newTask()} }window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys)},[view,opened,create]);
 const today=localDate();const archivedProjects=new Set(w.projects.filter(p=>p.archived).map(p=>p.id));const live=w.tasks.filter(t=>!t.deleted&&!t.archived&&!archivedProjects.has(t.projectId));
 const todayTasks=live.filter(t=>t.plannedDate===today || t.dueDate && t.dueDate<=today&&t.status!=='done');
 const active=w.sessions.find(s=>!s.endedAt);const resume=live.find(t=>t.id===active?.taskId)||live.filter(t=>t.status==='in_progress').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];
 const currentProject=w.projects.find(p=>p.id===view);const viewName=navigation.find(n=>n.id===view)?.name||({projects:'Projects',archive:'Archive',trash:'Trash'} as Record<string,string>)[view]||currentProject?.name||'All tasks';
 const tasks=useMemo(()=>{let list=w.tasks.filter(t=>view==='trash'?t.deleted:view==='archive'?!t.deleted&&(t.archived||archivedProjects.has(t.projectId)):!t.deleted&&!t.archived&&!archivedProjects.has(t.projectId));if(view==='today')list=list.filter(t=>t.plannedDate===today||t.dueDate&&t.dueDate<=today&&t.status!=='done');else if(view==='inbox')list=list.filter(t=>!t.projectId);else if(view==='upcoming')list=list.filter(t=>(t.dueDate>today||t.plannedDate>today)&&t.status!=='done');else if(currentProject)list=list.filter(t=>t.projectId===view);if(filter!=='all')list=list.filter(t=>filter==='open'?t.status!=='done':t.status===filter);if(priority!=='all')list=list.filter(t=>t.priority===priority);const q=query.toLowerCase().trim();if(q)list=list.filter(t=>[t.title,t.description,t.nextAction,...t.tags,w.projects.find(p=>p.id===t.projectId)?.name||'',...w.notes.filter(n=>n.taskId===t.id).map(n=>n.content)].join(' ').toLowerCase().includes(q));return list.sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='due'?(a.dueDate||'9999').localeCompare(b.dueDate||'9999'):sort==='priority'?['urgent','high','normal','low'].indexOf(a.priority)-['urgent','high','normal','low'].indexOf(b.priority):a.position-b.position)},[w,view,query,filter,priority,sort,today]);
 const openedTask=w.tasks.find(t=>t.id===opened);
 function navigate(next:string){setView(next);setSelected([]);setOpenMobile(false)}
 function newTask(status:Task['status']='todo'){setCaptureProject(currentProject?.id||'');setCaptureStatus(status);setCreate(true)}
 async function addTask(text:string,projectId:string,status:Task['status']='todo'){if(!text.trim())return false;const task=makeTask(text,projectId);task.status=status;if(view==='today')task.plannedDate=today;const success=await mutate(d=>{d.tasks.push(task)});if(success)toast.success('Task added');return success}
 async function patchTask(id:string,patch:Partial<Task>){return mutate(d=>{d.tasks=d.tasks.map(t=>t.id===id?{...t,...patch,updatedAt:new Date().toISOString()}:t)})}
 async function bulk(patch:Partial<Task>){if(await mutate(d=>{d.tasks=d.tasks.map(t=>selected.includes(t.id)?{...t,...patch,updatedAt:new Date().toISOString()}:t)})){setSelected([]);toast.success('Tasks updated')}}
 function move(id:string,delta:number){const ordered=tasks.filter(t=>t.status===tasks.find(x=>x.id===id)?.status);const index=ordered.findIndex(t=>t.id===id);const other=ordered[index+delta];if(!other)return;void mutate(d=>{const a=d.tasks.find(t=>t.id===id)!;const b=d.tasks.find(t=>t.id===other.id)!;[a.position,b.position]=[b.position,a.position]})}
 async function saveProject(){if(!project?.name.trim())return;if(await mutate(d=>{const i=d.projects.findIndex(p=>p.id===project.id);if(i<0)d.projects.push(project);else d.projects[i]=project})){setProject(null);toast.success('Project saved')}}
 const newProject=()=>setProject({id:crypto.randomUUID(),name:'',description:'',color:'#8571dd',archived:false});
 const webmcpRef=useRef({addTask,query,tasks,w,navigate});webmcpRef.current={addTask,query,tasks,w,navigate};
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'list_tasks',description:'Read the tasks in the currently visible filtered view.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({tasks:webmcpRef.current.tasks.map(({id,title,status,nextAction})=>({id,title,status,nextAction}))})},{name:'create_task',description:'Create and save a task in the inbox. Requires a nonempty title.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:240}},required:['title'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||!('title'in input)||typeof input.title!=='string'||!input.title.trim()||input.title.length>240)throw new Error('A title between 1 and 240 characters is required');const success=await webmcpRef.current.addTask(input.title,'');if(!success)throw new Error('Task could not be saved');return {saved:!demo,exampleMode:demo,title:input.title.trim()}}}];for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[demo]);
 const counts:Record<string,number>={today:todayTasks.filter(t=>t.status!=='done').length,inbox:live.filter(t=>!t.projectId&&t.status!=='done').length,upcoming:live.filter(t=>(t.dueDate>today||t.plannedDate>today)&&t.status!=='done').length,all:live.filter(t=>t.status!=='done').length};
 function taskMenu(t:Task){return <DropdownMenu><DropdownMenuTrigger asChild><button className="icon-btn" aria-label={`Actions for ${t.title}`}><MoreHorizontal size={17}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>setOpened(t.id)}>Open task</DropdownMenuItem><DropdownMenuItem onSelect={()=>void patchTask(t.id,{plannedDate:t.plannedDate===today?'':today})}>{t.plannedDate===today?'Remove from today':'Plan for today'}</DropdownMenuItem><DropdownMenuSeparator/>{statuses.map(s=><DropdownMenuItem key={s} onSelect={()=>void patchTask(t.id,{status:s})}>Move to {statusLabels[s]}</DropdownMenuItem>)}{sort==='position'&&<><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>move(t.id,-1)}><ArrowUp size={14}/>Move up</DropdownMenuItem><DropdownMenuItem onSelect={()=>move(t.id,1)}><ArrowDown size={14}/>Move down</DropdownMenuItem></>}<DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>void patchTask(t.id,{archived:!t.archived})}>{t.archived?'Unarchive':'Archive'}</DropdownMenuItem>{t.deleted?<DropdownMenuItem onSelect={()=>void patchTask(t.id,{deleted:false})}>Restore from trash</DropdownMenuItem>:<DropdownMenuItem onSelect={()=>{void patchTask(t.id,{deleted:true}).then(ok=>{if(ok)toast('Moved to trash',{action:{label:'Undo',onClick:()=>void patchTask(t.id,{deleted:false})}})})}}>Move to trash</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>}
 function taskMeta(t:Task){const p=w.projects.find(p=>p.id===t.projectId);return <div className="task-meta">{p?<><span className="project-square" style={{background:p.color}}/><span>{p.name}</span></>:<><Inbox size={11}/><span>Inbox</span></>}{t.nextAction&&<><span>·</span><span className="desktop-only">Next step ready</span></>}{t.tags.filter(Boolean).slice(0,2).map(tag=><span key={tag} className="tag">{tag}</span>)}</div>}
 function taskRow(t:Task,board=false){const notes=w.notes.filter(n=>n.taskId===t.id).length;return board?<article key={t.id} className="board-card"><div className="board-card-top"><Checkbox aria-label={`Complete ${t.title}`} checked={t.status==='done'} disabled={busy} onCheckedChange={checked=>void patchTask(t.id,{status:checked?'done':'todo'})}/>{taskMenu(t)}</div><button className="task-main" onClick={()=>setOpened(t.id)}><span className={'task-title '+(t.status==='done'?'done-title':'')}>{t.title}</span>{taskMeta(t)}</button><div className="board-card-foot"><span className={'task-meta priority-'+t.priority}><Flag size={12}/>{t.priority}</span>{t.dueDate&&<span className="task-meta">{prettyDate(t.dueDate)}</span>}{notes>0&&<span className="task-meta"><BookOpen size={12}/>{notes}</span>}</div></article>:<div key={t.id} className="task-row"><Checkbox aria-label={`Select ${t.title}`} checked={selected.includes(t.id)} onCheckedChange={v=>setSelected(s=>v?[...s,t.id]:s.filter(x=>x!==t.id))}/><button className="task-main" onClick={()=>setOpened(t.id)}><span className={'task-title '+(t.status==='done'?'done-title':'')}>{t.title}</span>{taskMeta(t)}</button><div className="task-right">{notes>0&&<span className="task-notes"><BookOpen size={13}/>{notes}</span>}{t.dueDate&&<span className={'date-label '+(t.dueDate<today&&t.status!=='done'?'date-overdue':'')}><CalendarDays size={12} className="inline mr-1"/>{t.dueDate===today?'Today':prettyDate(t.dueDate)}</span>}<Flag size={14} className={'priority-'+t.priority} aria-label={`${t.priority} priority`}/>{taskMenu(t)}</div></div>}
 return <><Sidebar><SidebarContent className="app-sidebar"><a href="/" className="brand" aria-label="Continuum home"><span className="brand-icon"><Layers size={21}/></span>continuum<span style={{color:'var(--primary)'}}>.</span></a><div className="workspace-name"><span className="avatar" style={{borderRadius:8}}>OW</span><span>My workspace</span></div><nav aria-label="Main navigation">{navigation.map(n=><button key={n.id} className={'nav-item '+(view===n.id?'active':'')} onClick={()=>navigate(n.id)}><n.icon size={18}/>{n.name}<small>{counts[n.id]||''}</small></button>)}</nav><div className="nav-heading"><button onClick={()=>navigate('projects')}>PROJECTS</button><button className="icon-btn" aria-label="New project" onClick={newProject}><Plus size={15}/></button></div><nav aria-label="Projects">{w.projects.filter(p=>!p.archived).map(p=><button key={p.id} onClick={()=>navigate(p.id)} className={'nav-item '+(view===p.id?'active':'')}><span className="project-square" style={{background:p.color}}/>{p.name}<small>{live.filter(t=>t.projectId===p.id&&t.status!=='done').length||''}</small></button>)}{!w.projects.length&&<button className="nav-item" onClick={newProject}><Plus size={15}/>Create a project</button>}</nav><div className="nav-heading">LIBRARY</div><button className={'nav-item '+(view==='archive'?'active':'')} onClick={()=>navigate('archive')}><Archive size={17}/>Archive</button><button className={'nav-item '+(view==='trash'?'active':'')} onClick={()=>navigate('trash')}><Trash2 size={17}/>Trash</button>{active&&<button className="active-session" onClick={()=>setOpened(active.taskId)}><Play size={14}/><span>Session in progress<br/><strong className="session-duration">{duration(active.startedAt)}</strong></span><ArrowRight size={15} className="ml-auto"/></button>}<SidebarFooter className="sidebar-foot"><div className="account"><span className="avatar">{identity.email?identity.email.slice(0,2).toUpperCase():'OW'}</span><span>{identity.email?identity.email.split('@')[0]:'Your workspace'}<small>{demo?'Example workspace':'Personal workspace'}</small></span><button className="icon-btn ml-auto" aria-label="Toggle color theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div></SidebarFooter></SidebarContent></Sidebar>
 <main className="flex min-w-0 flex-1 flex-col"><header className="topbar"><SidebarTrigger className="mobile-trigger"/><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14}/><span style={{color:'var(--foreground)'}}>{viewName}</span></div><div className="top-actions"><button className="icon-btn" aria-label="Search tasks" onClick={()=>search.current?.focus()}><Search size={18}/></button><span className="desktop-only muted" style={{fontSize:12}}>⌘ K</span><Button size="sm" onClick={()=>newTask()}><Plus size={16}/>New task</Button></div></header>
 {demo&&<div className="notice"><span>Example workspace · explore freely. Changes here are temporary.</span><a href="/signin-with-chatgpt?return_to=/" target="_top" className="underline whitespace-nowrap">Sign in to save</a></div>}
 <section className="content"><div className="eyebrow">{view==='today'?new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}):currentProject?'Project workspace':'Your workspace'}</div><div className="heading"><div><h1>{viewName}</h1><p>{view==='today'?'A little focus. A clear next step.':view==='inbox'?'Capture it now. Give it a home later.':view==='upcoming'?'A little breathing room for what’s ahead.':view==='all'?'Everything you’re working toward.':view==='archive'?'Finished chapters, kept within reach.':view==='trash'?'Restore a task together with its notes and sessions.':currentProject?.description||'A home for each part of your work.'}</p></div>{view==='projects'?<Button variant="outline" onClick={newProject}><Plus size={15}/>New project</Button>:currentProject?<Button variant="outline" onClick={()=>setProject({...currentProject})}><Settings2 size={15}/>Edit project</Button>:<span className="view-caption desktop-only">{tasks.filter(t=>t.status!=='done').length} tasks to focus on</span>}</div>
 {store.error&&<div className="error-banner" role="alert">{store.error}<div className="flex gap-3 mt-2"><button className="underline" onClick={()=>void store.load()}>Reload latest</button>{store.recovery&&<button className="underline" onClick={()=>void store.retry()}>Retry save</button>}</div></div>}
 {store.recovery&&<div className="notice mb-5"><span>A previous unsaved change is preserved.</span><div className="flex gap-3"><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(store.recovery,null,2)],{type:'application/json'}));a.download='continuum-recovered-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}>Download draft</button><button onClick={store.discardRecovery}>Discard draft</button></div></div>}
 {store.loading?<div className="space-y-5" aria-label="Loading workspace"><Skeleton className="h-28 w-full"/><Skeleton className="h-64 w-full"/></div>:<>
 {view==='today'&&resume&&<article className="resume-card"><span className="resume-icon"><RotateCcw size={21}/></span><div><div className="resume-label">{active?'SESSION IN PROGRESS':'PICK UP WHERE YOU LEFT OFF'}</div><h2>{resume.title}</h2><p><span className="next">Next:</span> {resume.nextAction||'Choose your next step and keep moving.'}</p></div><Button variant="outline" className="bg-card" onClick={()=>setOpened(resume.id)}>Resume task<ArrowRight size={15}/></Button></article>}
 {view==='projects'?<div className="project-grid">{w.projects.map(p=><article key={p.id} className="project-card"><span className="project-square inline-block" style={{background:p.color,width:17,height:17}}/><h2>{p.name}{p.archived?' · Archived':''}</h2><p>{p.description||'Your next chapter starts here.'}</p><span className="task-meta">{w.tasks.filter(t=>t.projectId===p.id&&!t.deleted&&t.status!=='done').length} open tasks</span><div className="project-card-actions"><Button size="sm" variant="outline" onClick={()=>navigate(p.archived?'archive':p.id)}>Open</Button><Button size="sm" variant="ghost" onClick={()=>setProject({...p})}>Edit</Button></div></article>)}{!w.projects.length&&<Blank title="Give your work a home" description="Projects keep related tasks together."><Button onClick={newProject}>Create a project</Button></Blank>}</div>:<>
 <div className="toolbar"><div className="toolbar-left"><Tabs value={layout} onValueChange={setLayout}><TabsList><TabsTrigger value="list"><List size={15}/>List</TabsTrigger><TabsTrigger value="board"><LayoutGrid size={15}/>Board</TabsTrigger></TabsList></Tabs><Choice label="Filter by status" value={filter} onChange={setFilter} options={[{value:'all',label:'All statuses'},{value:'open',label:'Open tasks'},...statuses.map(s=>({value:s,label:statusLabels[s]}))]}/></div><div className="toolbar-right"><div className="search-field"><Search size={15}/><input ref={search} aria-label="Search tasks and notes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks & notes…"/></div><Choice label="Filter by priority" value={priority} onChange={setPriority} options={[{value:'all',label:'Priority'},...['urgent','high','normal','low'].map(s=>({value:s,label:s[0].toUpperCase()+s.slice(1)}))]}/><Choice label="Sort tasks" value={sort} onChange={setSort} options={[{value:'position',label:'Manual order'},{value:'due',label:'Due date'},{value:'priority',label:'Priority'},{value:'title',label:'A–Z'}]}/></div></div>
 {selected.length>0&&<div className="bulkbar"><span>{selected.length} selected</span><Button size="sm" variant="outline" disabled={busy} onClick={()=>void bulk({status:'done'})}><CheckCheck size={14}/>Complete</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void bulk({plannedDate:today})}>Plan today</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void bulk(view==='trash'?{deleted:false}:view==='archive'?{archived:false}:{archived:true})}>{view==='trash'?'Restore':view==='archive'?'Unarchive':'Archive'}</Button><Choice label="Move selected tasks to project" value="__choose" onChange={v=>{if(v!=='__choose')void bulk({projectId:v})}} options={[{value:'__choose',label:'Move to project…'},{value:'',label:'Inbox'},...w.projects.filter(p=>!p.archived).map(p=>({value:p.id,label:p.name}))]}/><button className="icon-btn ml-auto" onClick={()=>setSelected([])}>Clear</button></div>}
 {tasks.length===0?<Blank title={query||filter!=='all'||priority!=='all'?'No matching tasks':view==='today'?'Make room for what matters':view==='trash'?'Nothing in the trash':'A fresh start'} description={query||filter!=='all'||priority!=='all'?'Try a different search or clear your filters.':view==='today'?'Add a task for today, or choose something from your inbox.':'Add your first task whenever you’re ready.'}><div className="flex gap-3 flex-wrap justify-center">{query||filter!=='all'||priority!=='all'?<Button variant="outline" onClick={()=>{setQuery('');setFilter('all');setPriority('all')}}>Clear filters</Button>:<Button onClick={()=>newTask()}><Plus size={16}/>Add a task</Button>}{w.tasks.length===0&&<Button variant="outline" disabled={busy} onClick={()=>void mutate(d=>Object.assign(d,sampleWorkspace()))}>Load example workspace</Button>}</div></Blank>:layout==='board'?<div className="board">{statuses.map(status=><div key={status} className="board-column"><h2 className="group-heading"><span className={'status-symbol '+status}/>{statusLabels[status]}<span className="count">{tasks.filter(t=>t.status===status).length}</span></h2>{tasks.filter(t=>t.status===status).map(t=>taskRow(t,true))}<button className="board-add" onClick={()=>newTask(status)}><Plus size={15}/>Add task</button></div>)}</div>:statuses.filter(status=>tasks.some(t=>t.status===status)).map(status=><section key={status} className="task-group"><h2 className="group-heading"><ChevronDown size={14}/><span className={'status-symbol '+status}/>{statusLabels[status]}<span className="count">{tasks.filter(t=>t.status===status).length}</span></h2><div className="task-list">{tasks.filter(t=>t.status===status).map(t=>taskRow(t))}</div></section>)}
 {!['trash','archive'].includes(view)&&<form className="quick-add" onSubmit={async e=>{e.preventDefault();if(await addTask(quick,currentProject?.id||''))setQuick('')}}><Plus size={18}/><input aria-label="Quick add task" maxLength={240} value={quick} onChange={e=>setQuick(e.target.value)} placeholder={view==='today'?'Add a task for today…':'Add a task…'}/>{quick?<Button size="sm" disabled={busy||!quick.trim()}>Add task</Button>:<span className="desktop-only" style={{fontSize:12}}>Enter ↵</span>}</form>}
 <div className="footnote"><BookOpen size={14}/><span>Every task has room for context. Open one to add notes or a next step.</span><span className="ml-auto desktop-only">N to create · ⌘ K to search</span></div>
 </>}
 </>}
 </section></main>
 {openedTask&&<TaskDetail key={openedTask.id} task={openedTask} workspace={w} busy={busy} identity={identity.userId||'example'} mutate={mutate} onClose={()=>setOpened('')} error={store.error}/>}
 <Dialog open={create} onOpenChange={setCreate}><DialogContent><DialogTitle>What’s on your mind?</DialogTitle><DialogDescription>A title is all you need. You can add the details later.</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await addTask(title,captureProject,captureStatus)){setTitle('');setCreate(false)}}}><Field label="Task title"><Input autoFocus required maxLength={240} aria-label="New task title" placeholder="Something to work toward…" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Project"><Choice label="New task project" value={captureProject} onChange={setCaptureProject} options={[{value:'',label:'Inbox'},...w.projects.filter(p=>!p.archived).map(p=>({value:p.id,label:p.name}))]} className="w-full"/></Field>{store.error&&<p className="error-banner" role="alert">{store.error}</p>}<div className="flex justify-end gap-2 mt-6"><Button type="button" variant="ghost" onClick={()=>setCreate(false)}>Cancel</Button><Button disabled={busy||!title.trim()}><Plus size={15}/>{busy?'Saving…':'Create task'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!project} onOpenChange={v=>{if(!v)setProject(null)}}><DialogContent><DialogTitle>{w.projects.some(p=>p.id===project?.id)?'Edit project':'A new project'}</DialogTitle><DialogDescription>Bring related tasks together.</DialogDescription>{project&&<form onSubmit={e=>{e.preventDefault();void saveProject()}}><Field label="Name"><Input aria-label="Project name" required maxLength={100} value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/></Field><Field label="Description"><Textarea aria-label="Project description" rows={3} value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/></Field><Field label="Color"><Input aria-label="Project color" type="color" value={project.color} onChange={e=>setProject({...project,color:e.target.value})} className="w-20"/></Field><label className="check-line"><Checkbox checked={project.archived} onCheckedChange={v=>setProject({...project,archived:!!v})}/>Archive project</label>{store.error&&<p className="error-banner" role="alert">{store.error}</p>}<div className="flex justify-end mt-5"><Button disabled={busy||!project.name.trim()}>Save project</Button></div></form>}</DialogContent></Dialog>
 </>;
}
