'use client';
import { useEffect,useRef,useState } from 'react';
import { Archive,ArrowRight,BookOpen,Check,Clock,FileText,Pause,Play,Plus,RotateCcw,Save,Trash2,X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { toast } from 'sonner';
import { Choice,Field,Blank,NoteContent,duration } from './workspace-parts';
import { localDate,statuses,statusLabels,type Task,type Workspace,type Note,type Session } from '@/lib/domain/workspace';
type Props={task:Task,workspace:Workspace,busy:boolean,identity:string,onClose:()=>void,mutate:(fn:(w:Workspace)=>void)=>Promise<boolean>,error:string};
export function TaskDetail({task,workspace,busy,identity,onClose,mutate,error}:Props){
 const [draft,setDraft]=useState<Task>(structuredClone(task));const [tab,setTab]=useState('details');const [checkText,setCheckText]=useState('');const [note,setNote]=useState<Note|null>(null);const [session,setSession]=useState<Session|null>(null);const [confirmDelete,setConfirmDelete]=useState(false);const [confirmSwitch,setConfirmSwitch]=useState(false);const [restored,setRestored]=useState(false);const [conflict,setConflict]=useState(false);const [noteConflict,setNoteConflict]=useState(false);const [saved,setSaved]=useState(false);const [,tick]=useState(0);
 const baseUpdatedAt=useRef(task.updatedAt);
 const key='continuum-task-draft-'+identity+'-'+task.id;const noteKey=key+'-note';
 useEffect(()=>{try{const raw=sessionStorage.getItem(key);if(raw){const recovered=JSON.parse(raw);const value=recovered.draft||recovered;if(value.id===task.id){baseUpdatedAt.current=recovered.baseUpdatedAt||value.updatedAt;setDraft(value);setRestored(true);setConflict(baseUpdatedAt.current!==task.updatedAt)}}const n=sessionStorage.getItem(noteKey);if(n){const recovered=JSON.parse(n);setNote(recovered);setNoteConflict(workspace.notes.some(x=>x.id===recovered.id&&x.updatedAt!==recovered.updatedAt));setTab('notebook')}}catch{}},[key,noteKey,task.id]);
 const dirty=JSON.stringify(draft)!==JSON.stringify(task);
 useEffect(()=>{try{if(dirty)sessionStorage.setItem(key,JSON.stringify({draft,baseUpdatedAt:baseUpdatedAt.current}));else sessionStorage.removeItem(key)}catch{}},[draft,dirty,key]);
 useEffect(()=>{try{if(note)sessionStorage.setItem(noteKey,JSON.stringify(note));else sessionStorage.removeItem(noteKey)}catch{}},[note,noteKey]);
 useEffect(()=>{const handle=(event:BeforeUnloadEvent)=>{if(dirty||note){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',handle);const timer=setInterval(()=>tick(x=>x+1),30000);return()=>{window.removeEventListener('beforeunload',handle);clearInterval(timer)}},[dirty,note]);
 const update=(patch:Partial<Task>)=>{setDraft(d=>({...d,...patch}));setSaved(false)};
 const persist=async()=>{if(conflict){toast.error('Review the recovered draft conflict first');return false;}const next={...draft,updatedAt:new Date().toISOString()};if(await mutate(w=>{w.tasks=w.tasks.map(t=>t.id===task.id?next:t)})){baseUpdatedAt.current=next.updatedAt;setDraft(next);setRestored(false);setSaved(true);toast.success('Task saved');return true}return false};
 const active=workspace.sessions.find(s=>!s.endedAt);const mine=active?.taskId===task.id;const sessions=workspace.sessions.filter(s=>s.taskId===task.id).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const notes=workspace.notes.filter(n=>n.taskId===task.id);
 const start=async(switching=false)=>{if(dirty&&!await persist())return;if(active&&!mine&&!switching){setConfirmSwitch(true);return}const now=new Date().toISOString();if(await mutate(w=>{if(switching)w.sessions=w.sessions.map(s=>s.endedAt?s:{...s,endedAt:now});w.sessions.push({id:crypto.randomUUID(),taskId:task.id,startedAt:now,endedAt:null,summary:'',blocker:'',nextAction:''});w.tasks=w.tasks.map(t=>t.id===task.id?{...t,status:'in_progress',updatedAt:now}:t)})){update({status:'in_progress',updatedAt:now});setConfirmSwitch(false);toast.success('Session started')}};
 const end=()=>{if(active)setSession({...active,endedAt:new Date().toISOString(),nextAction:draft.nextAction,blocker:draft.blocker})};
 const saveSession=async()=>{if(!session)return;const current=session;if(await mutate(w=>{const i=w.sessions.findIndex(s=>s.id===current.id);if(i>=0)w.sessions[i]=current;else w.sessions.push(current);if(current.endedAt)w.tasks=w.tasks.map(t=>t.id===task.id?{...draft,progress:current.summary||draft.progress,nextAction:current.nextAction,blocker:current.blocker,updatedAt:new Date().toISOString()}:t)})){if(current.endedAt)update({progress:current.summary||draft.progress,nextAction:current.nextAction,blocker:current.blocker});setSession(null);toast.success('Session saved')}};
 const saveNote=async()=>{if(!note?.content.trim()||noteConflict)return;const n={...note,updatedAt:new Date().toISOString()};if(await mutate(w=>{const i=w.notes.findIndex(x=>x.id===n.id);if(i>=0)w.notes[i]=n;else w.notes.push(n);w.tasks=w.tasks.map(t=>t.id===task.id?{...t,notebookEnabled:true}:t)})){update({notebookEnabled:true});setNote(null);toast.success('Note saved')}};
 const newNote=()=>{const now=new Date().toISOString();setNote({id:crypto.randomUUID(),taskId:task.id,label:'Note',content:'',createdAt:now,updatedAt:now})};
 const changeArchive=async()=>{if(await mutate(w=>{w.tasks=w.tasks.map(t=>t.id===task.id?{...t,archived:!t.archived}:t)}))onClose()};
 return <><Sheet open onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="detail-sheet"><div className="detail-head"><div className="detail-id">{workspace.projects.find(p=>p.id===task.projectId)?.name||'Inbox'} <span style={{margin:'0 8px'}}> / </span> Task</div><SheetTitle className="detail-title">{task.title}</SheetTitle><SheetDescription className="sr-only">Task details, optional notebook, and work sessions</SheetDescription><div className="detail-actions"><Button size="sm" variant={mine?'secondary':'default'} disabled={busy||task.deleted||task.archived} onClick={()=>mine?end():void start()}>{mine?<Pause size={14}/>:<Play size={14}/>} {mine?`End session · ${duration(active!.startedAt)}`:'Start session'}</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>update({plannedDate:draft.plannedDate===localDate()?'':localDate()})}>{draft.plannedDate===localDate()?<Check size={14}/>:<Plus size={14}/>}Plan for today</Button></div></div><div className="detail-body">
 {error&&<div role="alert" className="error-banner">{error}</div>}{conflict&&<div className="error-banner">The saved task changed since this draft. Review both versions before saving.<div className="flex gap-3 mt-2"><button onClick={()=>{baseUpdatedAt.current=task.updatedAt;setDraft(structuredClone(task));setConflict(false);setRestored(false)}}>Use saved task</button><button onClick={()=>{baseUpdatedAt.current=task.updatedAt;setConflict(false)}}>Keep my reviewed draft</button></div></div>}{restored&&<div className="notice">Unsaved task draft recovered.<button className="icon-btn" onClick={()=>{baseUpdatedAt.current=task.updatedAt;setDraft(structuredClone(task));setRestored(false);setConflict(false)}}>Discard</button></div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="w-full"><TabsTrigger value="details"><FileText size={14}/>Details</TabsTrigger><TabsTrigger value="notebook"><BookOpen size={14}/>Notebook {notes.length>0&&`(${notes.length})`}</TabsTrigger><TabsTrigger value="sessions"><Clock size={14}/>Sessions</TabsTrigger></TabsList>
 <TabsContent value="details"><Field label="Title"><Input aria-label="Task title" value={draft.title} maxLength={240} onChange={e=>update({title:e.target.value})}/></Field><Field label="Description"><Textarea aria-label="Task description" value={draft.description} placeholder="What does done look like?" onChange={e=>update({description:e.target.value})} rows={3}/></Field>
 <div className="field-grid"><Field label="Status"><Choice label="Task status" value={draft.status} onChange={v=>update({status:v as Task['status']})} options={statuses.map(s=>({value:s,label:statusLabels[s]}))} className="w-full"/></Field><Field label="Priority"><Choice label="Task priority" value={draft.priority} onChange={v=>update({priority:v as Task['priority']})} options={['low','normal','high','urgent'].map(s=>({value:s,label:s[0].toUpperCase()+s.slice(1)}))} className="w-full"/></Field><Field label="Project"><Choice label="Task project" value={draft.projectId} onChange={v=>update({projectId:v})} options={[{value:'',label:'Inbox'},...workspace.projects.map(p=>({value:p.id,label:p.name+(p.archived?' (archived)':'')}))]} className="w-full"/></Field><Field label="Due date"><Input type="date" aria-label="Due date" value={draft.dueDate} onChange={e=>update({dueDate:e.target.value})}/></Field><Field label="Planned for" hint="Your plan, separate from the deadline."><Input type="date" aria-label="Planned for" value={draft.plannedDate} onChange={e=>update({plannedDate:e.target.value})}/></Field><Field label="Tags"><Input aria-label="Tags" value={draft.tags.join(', ')} placeholder="Comma separated" onChange={e=>update({tags:e.target.value.split(',').map(t=>t.trimStart())})}/></Field></div>
 <div className="resume-box"><h3><RotateCcw size={16}/>Resume context</h3><Field label="Latest progress"><Textarea aria-label="Latest progress" rows={2} value={draft.progress} onChange={e=>update({progress:e.target.value})} placeholder="Where did you leave off?"/></Field><Field label="Next action"><Textarea aria-label="Next action" rows={2} value={draft.nextAction} onChange={e=>update({nextAction:e.target.value})} placeholder="One concrete step to take next"/></Field><Field label="Blocker"><Input aria-label="Blocker" value={draft.blocker} onChange={e=>update({blocker:e.target.value})} placeholder="Anything in the way?"/></Field>{notes.length>0&&<button className="icon-btn" onClick={()=>setTab('notebook')}><BookOpen size={14}/>&nbsp; {notes.length} related {notes.length===1?'note':'notes'} <ArrowRight size={14}/></button>}</div>
 <h3 className="field-label">Checklist · {draft.checklist.filter(c=>c.done).length}/{draft.checklist.length}</h3>{draft.checklist.map(c=><div key={c.id} className="check-line"><Checkbox aria-label={c.text} checked={c.done} onCheckedChange={v=>update({checklist:draft.checklist.map(x=>x.id===c.id?{...x,done:!!v}:x)})}/><span className={c.done?'done-title':''}>{c.text}</span><button aria-label={`Remove ${c.text}`} className="icon-btn" onClick={()=>update({checklist:draft.checklist.filter(x=>x.id!==c.id)})}><X size={13}/></button></div>)}<form className="check-line" onSubmit={e=>{e.preventDefault();if(checkText.trim()){update({checklist:[...draft.checklist,{id:crypto.randomUUID(),text:checkText.trim(),done:false}]});setCheckText('')}}}><Input aria-label="New checklist item" value={checkText} onChange={e=>setCheckText(e.target.value)} placeholder="Add a step…"/><Button size="icon" variant="outline" aria-label="Add checklist item"><Plus size={16}/></Button></form>
 <div className="save-line"><span role="status">{busy?'Saving…':dirty?'Unsaved changes · draft kept in this tab':saved?'Saved':'All changes saved'}</span><Button size="sm" disabled={busy||!draft.title.trim()||!dirty} onClick={()=>void persist()}><Save size={14}/>Save changes</Button></div>
 </TabsContent>
 <TabsContent value="notebook">{!draft.notebookEnabled&&!note?<Blank title="A little room for context" description="Keep notes, decisions, links, or an investigation here. Your task works just as well without them."><Button onClick={newNote}><Plus size={16}/>Add your first note</Button></Blank>:<><div className="detail-actions"><span className="view-caption">Notes & references</span><Button size="sm" className="ml-auto" variant="outline" disabled={!!note} onClick={newNote}><Plus size={14}/>Add note</Button></div>{notes.filter(n=>n.id!==note?.id).map(n=><article key={n.id} className="note-card"><div className="note-label"><span>{n.label} · {new Date(n.updatedAt).toLocaleDateString()}</span><button className="icon-btn" disabled={!!note} onClick={()=>setNote({...n})}>Edit</button></div><NoteContent content={n.content}/></article>)}</>}
 {noteConflict&&<div className="error-banner">This note changed after your draft was made.<div className="flex gap-3 mt-2"><button onClick={()=>{setNote(workspace.notes.find(n=>n.id===note?.id)||null);setNoteConflict(false)}}>Load saved note</button><button onClick={()=>setNoteConflict(false)}>Keep my reviewed draft</button></div></div>}{note&&<div className="note-card"><Choice label="Note type" value={note.label} onChange={v=>setNote({...note,label:v as Note['label']})} options={['Note','Investigation','Attempt','Result','Decision','Reference'].map(v=>({value:v,label:v}))}/><Field label="Note" hint="Use # headings, - lists, - [ ] checkboxes, [links](https://…), and fenced code blocks."><Textarea autoFocus aria-label="Note content" rows={10} value={note.content} onChange={e=>setNote({...note,content:e.target.value})} placeholder="Write something worth remembering…"/></Field><div className="save-line"><span>{busy?'Saving…':'Draft kept in this tab'}</span><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>setNote(null)}>Discard draft</Button><Button size="sm" disabled={busy||noteConflict||!note.content.trim()} onClick={()=>void saveNote()}>Save note</Button></div></div></div>}
 </TabsContent>
 <TabsContent value="sessions"><div className="detail-actions"><span className="view-caption">Your work, in context</span><Button className="ml-auto" size="sm" variant="outline" onClick={()=>setSession({id:crypto.randomUUID(),taskId:task.id,startedAt:new Date(Date.now()-1800000).toISOString(),endedAt:new Date().toISOString(),summary:'',blocker:'',nextAction:draft.nextAction})}><Plus size={14}/>Log session</Button></div>{sessions.length===0?<Blank title="Pick up where you left off" description="Start a session while you work, or log one afterward."/>:sessions.map(s=><div key={s.id} className="session-card"><div className="flex items-center justify-between gap-3"><span><Clock size={13} className="inline mr-2"/>{new Date(s.startedAt).toLocaleDateString()} · {duration(s.startedAt,s.endedAt)}{!s.endedAt?' · Active':''}</span><button className="icon-btn" onClick={()=>s.endedAt?setSession({...s}):end()}>{s.endedAt?'Edit':'End'}</button></div>{s.summary&&<p>{s.summary}</p>}{s.nextAction&&<p><strong>Next:</strong> {s.nextAction}</p>}{s.blocker&&<p><strong>Blocker:</strong> {s.blocker}</p>}</div>)}</TabsContent>
 </Tabs><div className="bottom-actions"><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void changeArchive()}><Archive size={14}/>{task.archived?'Unarchive':'Archive'}</Button>{task.deleted?<Button size="sm" variant="outline" onClick={async()=>{if(await mutate(w=>{w.tasks=w.tasks.map(t=>t.id===task.id?{...t,deleted:false}:t)}))onClose()}}><RotateCcw size={14}/>Restore task</Button>:<Button size="sm" variant="ghost" className="text-destructive" onClick={()=>setConfirmDelete(true)}><Trash2 size={14}/>Move to trash</Button>}</div></div></SheetContent></Sheet>
 <Dialog open={!!session} onOpenChange={v=>{if(!v)setSession(null)}}><DialogContent><DialogTitle>{session&&workspace.sessions.some(s=>s.id===session.id&&!s.endedAt)?'Finish this session':'Work session'}</DialogTitle><DialogDescription>Leave a clear starting point for next time.</DialogDescription>{session&&<div className="modal-form"><div className="field-grid"><Field label="Started"><Input type="datetime-local" aria-label="Session start" value={toInput(session.startedAt)} onChange={e=>{if(e.target.value)setSession({...session,startedAt:new Date(e.target.value).toISOString()})}}/></Field><Field label="Ended"><Input type="datetime-local" aria-label="Session end" value={toInput(session.endedAt||new Date().toISOString())} onChange={e=>{if(e.target.value)setSession({...session,endedAt:new Date(e.target.value).toISOString()})}}/></Field></div><Field label="What changed?"><Textarea aria-label="Session summary" rows={3} value={session.summary} onChange={e=>setSession({...session,summary:e.target.value})}/></Field><Field label="Next action"><Textarea aria-label="Session next action" rows={2} value={session.nextAction} onChange={e=>setSession({...session,nextAction:e.target.value})}/></Field><Field label="Blocker"><Input aria-label="Session blocker" value={session.blocker} onChange={e=>setSession({...session,blocker:e.target.value})}/></Field><Button disabled={busy} onClick={()=>void saveSession()}>Save session</Button></div>}</DialogContent></Dialog>
 <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogTitle>Move this task to trash?</AlertDialogTitle><AlertDialogDescription>The task, notebook, and sessions will stay available in Trash. You can restore them at any time.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(await mutate(w=>{w.tasks=w.tasks.map(t=>t.id===task.id?{...t,deleted:true}:t)}))onClose()}}>Move to trash</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={confirmSwitch} onOpenChange={setConfirmSwitch}><AlertDialogContent><AlertDialogTitle>Switch your active session?</AlertDialogTitle><AlertDialogDescription>End the session on “{workspace.tasks.find(t=>t.id===active?.taskId)?.title}” and start working on this task. You can edit the previous session summary afterward.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep current session</AlertDialogCancel><AlertDialogAction onClick={()=>void start(true)}>Switch task</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
function toInput(value:string){const d=new Date(value);return `${localDate(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
