'use client';
import { Fragment,useState,type ReactNode } from 'react';
import { Copy,Check,NotebookPen } from 'lucide-react';
import { toast } from 'sonner';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia } from '@/components/ui/empty';
export function Choice({value,onChange,options,label,className=''}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string,className?:string}){return <Select value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger aria-label={label} className={className}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value||'__none'} value={o.value||'__none'}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Field({label,children,hint}:{label:string,children:ReactNode,hint?:string}){return <div className="field"><div className="field-label">{label}</div>{children}{hint&&<span className="field-hint">{hint}</span>}</div>}
export function Blank({title,description,children}:{title:string,description:string,children?:ReactNode}){return <Empty className="empty-card"><EmptyHeader><EmptyMedia variant="icon"><NotebookPen/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>}
function Code({language,code}:{language:string,code:string}){const [copied,setCopied]=useState(false);return <div><div className="note-label"><span>{language||'text'}</span><button className="icon-btn" aria-label="Copy code" onClick={async()=>{try{await navigator.clipboard.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{toast.error('Could not access the clipboard')}}}>{copied?<Check size={14}/>:<Copy size={14}/>}</button></div><pre><code>{code}</code></pre></div>}
function Inline({text}:{text:string}){return <>{text.split(/(\[[^\]]+\]\(https?:\/\/[^\s)]+\))/g).map((s,i)=>{const m=s.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);return m?<a key={i} href={m[2]} target="_blank" rel="noopener noreferrer">{m[1]}</a>:<Fragment key={i}>{s}</Fragment>})}</>}
// All source is rendered as React text. No raw HTML or unsafe URL protocols.
export function NoteContent({content}:{content:string}){return <div className="note-content">{content.split(/```/g).map((part,i)=>i%2?<Code key={i} language={part.split('\n')[0]} code={part.split('\n').slice(1).join('\n')}/>:<div key={i}>{part.split('\n').map((line,j)=>line.startsWith('#')?<h3 key={j}><Inline text={line.replace(/^#+\s*/,'')}/></h3>:/^- \[[ x]\] /.test(line)?<div key={j}>{line[3]==='x'?'☑':'☐'} <Inline text={line.slice(6)}/></div>:line.startsWith('- ')?<div key={j}>• <Inline text={line.slice(2)}/></div>:<p key={j} style={{minHeight:line?undefined:10}}><Inline text={line}/></p>)}</div>)}</div>}
export const duration=(start:string,end?:string|null)=>{const minutes=Math.max(0,Math.floor(((end?new Date(end).getTime():Date.now())-new Date(start).getTime())/60000));return minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60}m`};
export const prettyDate=(s:string)=>s?new Date(s+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';
